# -*- coding: utf-8 -*-
"""Colab활용.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nNPAHn6gvD2tkmK09xTcxMn-alGki4c7
"""

print('안녕하세요.')

from google.colab import files
myfile = files.upload()

import io
import pandas as pd

myfile

data = pd.read_csv(io.BytesIO(myfile['testdata.csv']))

data.head()

from google.colab import drive
drive.mount('/content/drive')

filename = '/content/drive/MyDrive/testdata.csv'

data = pd.read_csv(filename)

data.head()



"""print('안녕하세요')"""